<?php
date_default_timezone_set("Asia/Kolkata");

require_once '../../dompdf/autoload.inc.php';
use Dompdf\Dompdf;

include("../db.php");

$type  = $_GET['type'] ?? '';
$start = $_GET['start'] ?? '';
$end   = $_GET['end'] ?? '';

/* REPORT NAME */

$reportName = "Orders Report";

if($type=="daily") $reportName="Daily Orders Report";
if($type=="weekly") $reportName="Weekly Orders Report";
if($type=="monthly") $reportName="Monthly Orders Report";
if($type=="yearly") $reportName="Yearly Orders Report";

/* DATA QUERY */
$tableWhere = "WHERE 1";

if($type=="weekly"){
$tableWhere .= " AND YEARWEEK(Order_Date,1)=YEARWEEK(CURDATE(),1)";
}

$query = mysqli_query($connection,"
SELECT 
o.Order_Id,
o.Order_Date,
o.Total_Amount,
u.First_Name,
u.Last_Name
FROM `order` o
LEFT JOIN user_details u 
ON o.User_Id = u.User_Id
$tableWhere
ORDER BY o.Order_Date DESC

");



$totalOrders=0;
$totalRevenue=0;

$rows="";

while($row=mysqli_fetch_assoc($query)){

$totalOrders++;
$totalRevenue+=$row['Total_Amount'];

$rows.="
<tr>
<td>{$row['Order_Id']}</td>
<td>{$row['First_Name']} {$row['Last_Name']}</td>
<td>{$row['Order_Date']}</td>
<td>₹".number_format($row['Total_Amount'],2)."</td>

</tr>
";

}
$logo = "../../home_page/logo.png";

// $logo = $_SERVER['DOCUMENT_ROOT']."/GitHub/gift-shop-website/home page/logo.png";

/* CHART IMAGE */

$chartImage = "chart.png"; // saved chart image from JS

/* HTML */

$html="

<style>

body{
font-family:Arial;
margin:10px;
}


.header{
display:flex;
align-items:center;
border-bottom:2px solid #7e2626d5;
padding-bottom:10px;
margin-bottom:20px;
}

.logo{
width:60px;
}

.company{
margin-left:15px;
}

.company h2{
margin:0;
color:#7e2626d5;
}

.meta{
margin-top:10px;
font-size:12px;
}

.summary{
background:#f8f3ee;
padding:10px;
margin:15px 0;
}

table{
width:100%;
border-collapse:collapse;
}

th{
background:#7e2626d5;
color:white;
padding:8px;
}

td{
padding:8px;
border:1px solid #ddd;
}

.chart{
margin:20px 0;
text-align:center;
}

</style>


<div class='header'>

<img src='$logo' class='logo' width:'60'>

<div class='company'>
<h2>GiftShop</h2>
<div>201/A Maninagar, Ahmedabad</div>
<div>Email: giftshopmaninagar@gmail.com</div>
<div>Phone: 9876543210</div>
</div>

</div>


<h3>$reportName</h3>

<div class='meta'>
Generated Time: ".date("d M Y h:i A")."

</div>


<div class='summary'>
Total Orders: $totalOrders <br>
Total Revenue: ₹".number_format($totalRevenue,2)."
</div>


<div class='chart'>
<img src='$chartImage' width='500'>
</div>


<table>

<tr>
<th>Order ID</th>
<th>Customer</th>
<th>Date</th>
<th>Amount</th>

</tr>

$rows

</table>
<div style='text-align:center;font-size:11px;margin-top:20px;color:#666;'>
Generated by GiftShop Admin Panel
</div>


";

/* GENERATE PDF */

$dompdf = new Dompdf();

$dompdf->loadHtml($html);

$dompdf->setPaper('A4','portrait');

$dompdf->render();

$dompdf->stream("orders_report.pdf",array("Attachment"=>0));

?>
