<?php
date_default_timezone_set("Asia/Kolkata");

require_once '../../dompdf/autoload.inc.php';
use Dompdf\Dompdf;
use Dompdf\Options;

include("../db.php");

/* ================= GET FILTER ================= */

$statusFilter = $_GET['status'] ?? '';

/* ================= REPORT NAME ================= */

$reportName = "Delivery Status Report";

if($statusFilter){
$reportName .= " - ".$statusFilter;
}

/* ================= FILTER CONDITION ================= */

$whereCondition = "";

if($statusFilter != ""){

if($statusFilter=="CONFIRM"){
$whereCondition = "WHERE d.Delivery_Status IS NULL";
}
else{
$whereCondition = "WHERE d.Delivery_Status='$statusFilter'";
}

}

/* ================= FETCH DATA ================= */

$query = mysqli_query($connection,"

SELECT 
o.Order_Id,
CONCAT(u.First_Name,' ',u.Last_Name) AS customer,
d.Delivery_Address,
a.Area_Name,
DATE(o.Order_Date) AS order_date,
o.Total_Amount,

CASE
WHEN d.Delivery_Status='Delivered' THEN 'Delivered'
WHEN d.Delivery_Status='Out for Delivery' THEN 'Out for Delivery'
WHEN d.Delivery_Status='Packed' THEN 'Packed'
ELSE 'CONFIRM'
END AS status

FROM `order` o

LEFT JOIN delivery_details d 
ON o.Order_Id=d.Order_Id

LEFT JOIN user_details u
ON o.User_Id=u.User_Id

LEFT JOIN area_details a
ON d.Area_Id=a.Area_Id

$whereCondition

ORDER BY o.Order_Date DESC
");

/* ================= GENERATE TABLE ================= */

$rows="";
$totalOrders=0;
$totalAmount=0;

while($row=mysqli_fetch_assoc($query)){

$totalOrders++;
$totalAmount += $row['Total_Amount'];

$rows .= "

<tr>
<td>{$row['Order_Id']}</td>
<td>{$row['customer']}</td>
<td>{$row['Delivery_Address']}</td>
<td>{$row['Area_Name']}</td>
<td>{$row['order_date']}</td>
<td>₹".number_format($row['Total_Amount'],2)."</td>
<td>{$row['status']}</td>
</tr>

";

}

/* ================= CHART IMAGE ================= */

$chartImage = $_POST['chart_image'] ?? "";

/* ================= PDF HTML ================= */

$html="

<style>

@page{
margin:15px 20px 70px 20px;
}

body{
font-family: DejaVu Sans, sans-serif;
font-size:12px;
color:#333;
}

/* HEADER */

.header{
border-bottom:2px solid #7e2626;
padding-bottom:6px;
margin-bottom:12px;
}

.company h2{
margin:0;
color:#7e2626;
font-size:18px;
}

.company div{
font-size:11px;
}

.meta{
font-size:11px;
margin-top:6px;
}

/* SUMMARY */

.summary{
background:#f8f3ee;
padding:6px;
margin:10px 0;
font-size:12px;
border-left:4px solid #7e2626;
}

/* TABLE */

table{
width:100%;
border-collapse:collapse;
margin-top:10px;
page-break-inside:auto;
}

tr{
page-break-inside:avoid;
page-break-after:auto;
}

td,th{
page-break-inside:avoid;
}

thead{
display:table-header-group;
}

tfoot{
display:table-footer-group;
}

th{
background:#7e2626;
color:white;
padding:6px;
font-size:12px;
}

td{
padding:5px;
border:1px solid #ddd;
font-size:11px;
text-align:center;
}

/* CHART */

.chart{
text-align:center;
margin:12px 0;
}

/* FOOTER */

.footer{
position:fixed;
bottom:-40px;
left:0;
right:0;
text-align:center;
font-size:10px;
color:#666;
border-top:1px solid #ccc;
}

</style>


<div class='header'>
<div class='company'>
<h2>GiftShop</h2>
<div>201/A, Maninagar, Ahmedabad</div>
<div>Email: giftshopmaninagar@gmail.com | Phone: 9876543210</div>
</div>
</div>

<h3>$reportName</h3>

<div class='meta'>
Generated : ".date("d M Y h:i A")."
</div>

<div class='summary'>
<b>Total Orders :</b> $totalOrders
&nbsp;&nbsp;&nbsp;
<b>Total Amount :</b> ₹".number_format($totalAmount,2)."
</div>
";

/* ================= ADD CHART ================= */

if($chartImage){
$html .= "

<div class='chart'>
<img src='$chartImage' width='420'>
</div>

";
}

$html .= "

<table>

<thead>

<tr>
<th>Order ID</th>
<th>Customer</th>
<th>Address</th>
<th>Area</th>
<th>Date</th>
<th>Amount</th>
<th>Status</th>
</tr>

</thead>

<tbody>

$rows

</tbody>

<tfoot>

<tr>
<td colspan='5' style='text-align:right;font-weight:bold;background:#f8f3ee'>
Total Amount
</td>

<td style='font-weight:bold;background:#f8f3ee'>
₹".number_format($totalAmount,2)."
</td>

<td></td>

</tr>

</tfoot>

</table>

<div class='footer'>
Generated by GiftShop Admin Panel
</div>

";

/* ================= GENERATE PDF ================= */

$options = new Options();
$options->set('isRemoteEnabled', true);

$dompdf = new Dompdf($options);

$dompdf->loadHtml($html);
$dompdf->setPaper('A4','portrait');
$dompdf->render();

$dompdf->stream("delivery_status_report.pdf",["Attachment"=>0]);

?>