<?php
date_default_timezone_set("Asia/Kolkata");

require_once '../../dompdf/autoload.inc.php';
use Dompdf\Dompdf;
use Dompdf\Options;

include("../db.php");

/* ================= GET FILTER VALUES ================= */

$type  = $_GET['type'] ?? '';
$limit = $_GET['limit'] ?? '';

/* ================= REPORT NAME ================= */

$reportName="Top / Least Selling Products Report";

if($type=="top"){
$reportName="Top Selling Products Report";
}

if($type=="low"){
$reportName="Least Selling Products Report";
}

/* ================= QUERY ================= */

$query="

SELECT 
c.Category_Name,
p.Product_Id,
p.Product_Name,
SUM(oi.Quantity) AS Total_Sold

FROM order_item oi

JOIN product_details p 
ON oi.Product_Id = p.Product_Id

JOIN category_details c 
ON p.Category_Id = c.Category_Id

GROUP BY p.Product_Id

";

/* FILTER */

if($type=="top" && $limit){
$query.=" ORDER BY Total_Sold DESC LIMIT $limit";
}
elseif($type=="low" && $limit){
$query.=" ORDER BY Total_Sold ASC LIMIT $limit";
}
else{
$query.=" ORDER BY c.Category_Name,p.Product_Name";
}

$result=mysqli_query($connection,$query);

/* ================= BUILD TABLE ================= */

$currentCategory="";
$rows="";
$categoryTotal=0;
$grandTotal=0;

while($row=mysqli_fetch_assoc($result)){

if($currentCategory!=$row['Category_Name']){

if($currentCategory!=""){

$rows.="
<tr class='category-total'>
<td colspan='2'>Category Total</td>
<td>$categoryTotal</td>
</tr>
";

$categoryTotal=0;
}

$currentCategory=$row['Category_Name'];

$rows.="

<tr class='category-row'>
<td colspan='3'>
Category : $currentCategory
</td>
</tr>

";
}

$rows.="

<tr>

<td>{$row['Product_Id']}</td>
<td>{$row['Product_Name']}</td>
<td>{$row['Total_Sold']}</td>

</tr>

";

$categoryTotal+=$row['Total_Sold'];
$grandTotal+=$row['Total_Sold'];

}

/* LAST CATEGORY TOTAL */

if($currentCategory!=""){

$rows.="

<tr class='category-total'>
<td colspan='2'>Category Total</td>
<td>$categoryTotal</td>
</tr>

";

}

/* ================= PDF HTML ================= */

$html="

<style>

@page{
margin:15px 20px 70px 20px;
}

body{
font-family:DejaVu Sans,sans-serif;
font-size:12px;
color:#333;
}

/* HEADER */

.header{
border-bottom:2px solid #7e2626;
padding-bottom:6px;
margin-bottom:12px;
}

.company h2{
margin:0;
color:#7e2626;
font-size:18px;
}

.company div{
font-size:11px;
}

.meta{
font-size:11px;
margin-top:6px;
}

/* SUMMARY */

.summary{
background:#f8f3ee;
padding:6px;
margin:10px 0;
font-size:12px;
border-left:4px solid #7e2626;
}

/* TABLE */

table{
width:100%;
border-collapse:collapse;
margin-top:10px;
page-break-inside:auto;
}

tr{
page-break-inside:avoid;
page-break-after:auto;
}

td,th{
page-break-inside:avoid;
}

thead{
display:table-header-group;
}

tfoot{
display:table-footer-group;
}

.category-row{
background:#f8f3ee;
font-weight:bold;
color:#7e2626;
}

.category-total{
background:#f7eaea;
font-weight:bold;
}

th{
background:#7e2626;
color:white;
padding:6px;
font-size:12px;
}

td{
padding:5px;
border:1px solid #ddd;
font-size:11px;
text-align:center;
}

/* FOOTER */

.footer{
position:fixed;
bottom:-40px;
left:0;
right:0;
text-align:center;
font-size:10px;
color:#666;
border-top:1px solid #ccc;
}

</style>

<div class='header'>

<div class='company'>
<h2>GiftShop</h2>
<div>201/A, Maninagar, Ahmedabad</div>
<div>Email: giftshopmaninagar@gmail.com | Phone: 9876543210</div>
</div>

</div>

<h3>$reportName</h3>

<div class='meta'>
Generated : ".date("d M Y h:i A")."
</div>

<div class='summary'>
<b>Total Products Sold :</b> $grandTotal
</div>

<table>

<thead>

<tr>
<th>Product ID</th>
<th>Product Name</th>
<th>Total Sold</th>
</tr>

</thead>

<tbody>

$rows

</tbody>

<tfoot>

<tr>

<td colspan='2' style='text-align:right;font-weight:bold;background:#f8f3ee'>
Grand Total Sold
</td>

<td style='font-weight:bold;background:#f8f3ee'>
$grandTotal
</td>

</tr>

</tfoot>

</table>

<div class='footer'>
Generated by GiftShop Admin Panel
</div>

";

/* ================= GENERATE PDF ================= */

$options=new Options();
$options->set('isRemoteEnabled',true);

$dompdf=new Dompdf($options);

$dompdf->loadHtml($html);

$dompdf->setPaper('A4','portrait');

$dompdf->render();

$dompdf->stream("top_low_selling_products_report.pdf",["Attachment"=>0]);

?>