<?php
date_default_timezone_set("Asia/Kolkata");

require_once '../../dompdf/autoload.inc.php';

use Dompdf\Dompdf;
use Dompdf\Options;

include("../db.php");

/* ================= GET FILTER VALUES ================= */

$type  = $_GET['type'] ?? '';
$limit = $_GET['limit'] ?? '';

/* ================= REPORT NAME ================= */

$reportName = "Stock Report";

if($type=="high"){
$reportName = "Highest Stock Report";
}
elseif($type=="low"){
$reportName = "Lowest Stock Report";
}

/* ================= QUERY ================= */

$query = "
SELECT 
c.Category_Name,
p.Product_Id,
p.Product_Name,
s.Stock_Available,
s.Last_Update
FROM stock_details s
JOIN product_details p ON s.Product_Id = p.Product_Id
JOIN category_details c ON p.Category_Id = c.Category_Id
";

/* FILTER */

if($type=="high" && $limit){
$query .= " ORDER BY s.Stock_Available DESC LIMIT $limit";
}
elseif($type=="low" && $limit){
$query .= " ORDER BY s.Stock_Available ASC LIMIT $limit";
}
else{
$query .= " ORDER BY c.Category_Name, p.Product_Name";
}

$result = mysqli_query($connection,$query);

/* ================= PROCESS DATA ================= */

$currentCategory="";
$categoryTotal=0;
$grandTotal=0;

$rows="";

while($row=mysqli_fetch_assoc($result)){

if($currentCategory != $row['Category_Name']){

if($currentCategory!=""){

$rows .= "
<tr style='background:#f7eaea;font-weight:bold'>
<td colspan='3' style='text-align:right'>Category Total</td>
<td>$categoryTotal</td>
</tr>
";

$categoryTotal=0;
}

$currentCategory=$row['Category_Name'];

$rows .= "
<tr style='background:#f8f3ee;font-weight:bold;color:#7e2626'>
<td colspan='4'>Category : {$currentCategory}</td>
</tr>
";
}

$date = date("d M Y",strtotime($row['Last_Update']));

$rows .= "
<tr>
<td>{$row['Product_Id']}</td>
<td>{$row['Product_Name']}</td>
<td>$date</td>
<td>{$row['Stock_Available']}</td>
</tr>
";

$categoryTotal += $row['Stock_Available'];
$grandTotal += $row['Stock_Available'];

}

/* LAST CATEGORY TOTAL */

if($currentCategory!=""){

$rows .= "
<tr style='background:#f7eaea;font-weight:bold'>
<td colspan='3' style='text-align:right'>Category Total</td>
<td>$categoryTotal</td>
</tr>
";

}

/* ================= PDF HTML ================= */

$html="

<style>

/* PAGE */

@page{
margin:15px 20px 70px 20px;
}

body{
font-family: DejaVu Sans, sans-serif;
font-size:12px;
color:#333;
}

/* HEADER */

.header{
border-bottom:2px solid #7e2626;
padding-bottom:6px;
margin-bottom:12px;
}

.company h2{
margin:0;
color:#7e2626;
font-size:18px;
}

.company div{
font-size:11px;
}

/* META */

.meta{
font-size:11px;
margin-top:6px;
}

/* SUMMARY */

.summary{
background:#f8f3ee;
padding:6px;
margin:10px 0;
font-size:12px;
border-left:4px solid #7e2626;
}

/* TABLE */

table{
width:100%;
border-collapse:collapse;
margin-top:10px;
page-break-inside:auto;
}

tr{
page-break-inside:avoid;
page-break-after:auto;
}

td,th{
page-break-inside:avoid;
}

thead{
display:table-header-group;
}

tfoot{
display:table-footer-group;
}

th{
background:#7e2626;
color:white;
padding:6px;
font-size:12px;
}

td{
padding:5px;
border:1px solid #ddd;
font-size:11px;
text-align:center;
}

/* FOOTER */

.footer{
position:fixed;
bottom:-40px;
left:0;
right:0;
text-align:center;
font-size:10px;
color:#666;
border-top:1px solid #ccc;
}

</style>


<div class='header'>

<div class='company'>
<h2>GiftShop</h2>
<div>201/A, Maninagar, Ahmedabad</div>
<div>Email: giftshopmaninagar@gmail.com | Phone: 9876543210</div>
</div>

</div>

<h3>$reportName</h3>

<div class='meta'>
Generated : ".date("d M Y h:i A")."
</div>

<div class='summary'>
<b>Total Stock :</b> $grandTotal
</div>

<table>

<thead>

<tr>
<th>Product ID</th>
<th>Product Name</th>
<th>Last Update</th>
<th>Stock Available</th>
</tr>

</thead>

<tbody>

$rows

</tbody>

<tfoot>

<tr>

<td colspan='3' style='text-align:right;font-weight:bold;background:#f8f3ee'>
Grand Total Stock
</td>

<td style='font-weight:bold;background:#f8f3ee'>
$grandTotal
</td>

</tr>

</tfoot>

</table>

<div class='footer'>
Generated by GiftShop Admin Panel
</div>

";

/* ================= GENERATE PDF ================= */

$options = new Options();
$options->set('isRemoteEnabled', true);

$dompdf = new Dompdf($options);

$dompdf->loadHtml($html);
$dompdf->setPaper('A4','portrait');

$dompdf->render();

$dompdf->stream("stock_report.pdf",["Attachment"=>0]);

?>
