<?php
date_default_timezone_set("Asia/Kolkata");

require_once '../../dompdf/autoload.inc.php';

use Dompdf\Dompdf;
use Dompdf\Options;

include("../db.php");
$productFilter = $_GET['product_id'] ?? '';
$periodFilter  = $_GET['period'] ?? '';
$chartImage    = $_POST['chart_image'] ?? '';

/* PRODUCT NAME */

$productName = "";

if($productFilter){

$q = mysqli_query($connection,"
SELECT Product_Name 
FROM product_details 
WHERE Product_Id='$productFilter'
");

if($row=mysqli_fetch_assoc($q)){
$productName=$row['Product_Name'];
}

}

/*  REPORT NAME */

$reportName = "Product-wise Sales Report";

if($periodFilter=="daily")   $reportName="Daily Product-wise Sales Report";
if($periodFilter=="weekly")  $reportName="Weekly Product-wise Sales Report";
if($periodFilter=="monthly") $reportName="Monthly Product-wise Sales Report";
if($periodFilter=="yearly")  $reportName="Yearly Product-wise Sales Report";

$periodCondition="";

if($periodFilter=="daily"){
$periodCondition="AND DATE(o.Order_Date)=CURDATE()";
}

elseif($periodFilter=="weekly"){
$periodCondition="AND YEARWEEK(o.Order_Date,1)=YEARWEEK(CURDATE(),1)";
}

elseif($periodFilter=="monthly"){
$periodCondition="AND MONTH(o.Order_Date)=MONTH(CURDATE())
AND YEAR(o.Order_Date)=YEAR(CURDATE())";
}

elseif($periodFilter=="yearly"){
$periodCondition="AND YEAR(o.Order_Date)=YEAR(CURDATE())";
}

/* FETCH ORDER*/

$query=mysqli_query($connection,"
SELECT 
o.Order_Id,
CONCAT(u.First_Name,' ',u.Last_Name) AS customer,
o.Order_Date,
SUM(oi.Quantity * oi.Price_Snapshot) AS revenue
FROM order_item oi
JOIN `order` o ON oi.Order_Id=o.Order_Id
JOIN user_details u ON o.User_Id=u.User_Id
WHERE oi.Product_Id='$productFilter'
$periodCondition
GROUP BY o.Order_Id
ORDER BY o.Order_Date DESC
");

/* CALCULATE TOTAL */

$totalOrders=0;
$totalRevenue=0;

$rows="";

while($row=mysqli_fetch_assoc($query)){

$totalOrders++;

$totalRevenue += $row['revenue'];

$date=date("d M Y H:i",strtotime($row['Order_Date']));

$rows.="
<tr>
<td>{$row['Order_Id']}</td>
<td>{$row['customer']}</td>
<td>$date</td>
<td>₹".number_format($row['revenue'],2)."</td>
</tr>
";

}

/* LOGO*/

$logoPath = __DIR__ . "/../../home page/logo.svg";

if(file_exists($logoPath)){
$logoData=base64_encode(file_get_contents($logoPath));
$logoPath='data:image/png;base64,'.$logoData;
}



$html="

<style>

@page{
margin:15px 20px 70px 20px;
}

body{
font-family: DejaVu Sans, sans-serif;
font-size:12px;
color:#333;
}
.header{
border-bottom:2px solid #7e2626;
padding-bottom:8px;
margin-bottom:12px;
position:relative;
padding-left:80px;
min-height:70px;
}

.header img{
position:absolute;
left:-10px;
top:-10px;
height:50px;
}

.company h2{
margin:0;
color:#7e2626;
font-size:18px;
}

.company div{
font-size:11px;
margin-top:2px;
}

.meta{
font-size:11px;
margin-top:6px;
}

/* SUMMARY */

.summary{
background:#f8f3ee;
padding:6px;
margin:10px 0;
font-size:12px;
border-left:4px solid #7e2626;
}

/* TABLE */

table{
width:100%;
border-collapse:collapse;
margin-top:10px;
}

th{
background:#7e2626;
color:white;
padding:6px;
font-size:12px;
}

td{
padding:5px;
border:1px solid #ddd;
font-size:11px;
text-align:center;
}

/* CHART */

.chart{
text-align:center;
margin:12px 0;
}

/* FOOTER */

.footer{
position:fixed;
bottom:-40px;
left:0;
right:0;
text-align:center;
font-size:10px;
color:#666;
border-top:1px solid #ccc;
}

</style>


<div class='header'>

<img src='$logoPath'>

<div class='company'>

<h2>GiftShop</h2>

<div>201/A,Business Park,GiftShop,Maninagar,Ahmedabad,Gujarat</div>

<div>Email: giftshopmaninagar@gmail.com | Phone:+91 9876543210</div>

</div>

</div>


<h3>$reportName</h3>

<div class='meta'>
Generated : ".date("d M Y h:i A")."
</div>


<div class='summary'>

<b>Product :</b> $productName
&nbsp;&nbsp;&nbsp;

<b>Total Orders :</b> $totalOrders
&nbsp;&nbsp;&nbsp;

<b>Total Revenue :</b> ₹".number_format($totalRevenue,2)."

</div>


<div class='chart'>

<img src='$chartImage' width='420'>

</div>


<table>

<thead>

<tr>

<th>Order ID</th>

<th>Customer</th>

<th>Date</th>

<th>Revenue</th>

</tr>

</thead>

<tbody>

$rows

</tbody>


<tfoot>

<tr>

<td colspan='3' style='text-align:right;font-weight:bold;background:#f8f3ee'>

Total Revenue

</td>

<td style='font-weight:bold;background:#f8f3ee'>

₹".number_format($totalRevenue,2)."

</td>

</tr>

</tfoot>

</table>


<div class='footer'>

Generated by GiftShop Admin Panel

</div>

";

/*  GENERATE PDF */

$options = new Options();

$options->set('isRemoteEnabled', true);

$options->set('isHtml5ParserEnabled', true);

$options->set('isPhpEnabled', true);

$dompdf = new Dompdf($options);

$dompdf->loadHtml($html);

$dompdf->setPaper('A4','portrait');

$dompdf->render();

$dompdf->stream("product_sales_report.pdf",["Attachment"=>0]);

?>
