<?php
session_start();

require_once '../../dompdf/autoload.inc.php';
use Dompdf\Dompdf;

include(__DIR__ . '/../db.php');

$period = $_GET['period'] ?? '';
$month  = $_GET['month'] ?? '';
$chart  = $_POST['chart_image'] ?? '';

/* ================= REPORT RANGE ================= */

$reportRange = "All Time";

if($period == "daily"){
    $reportRange = "Today";
}
elseif($period == "weekly"){
    $reportRange = "This Week";
}
elseif($period == "monthly"){
    $reportRange = "This Month";
}
elseif($period == "yearly"){

    if($month){
        $reportRange = date("F", mktime(0,0,0,$month,10))." ".date("Y");
    }else{
        $reportRange = "Year ".date("Y");
    }

}

/* ================= WHERE CONDITION ================= */

$whereCondition = "";

if($period=="daily"){
    $whereCondition = "WHERE DATE(o.Order_Date)=CURDATE()";
}

elseif($period=="weekly"){
    $whereCondition = "WHERE YEARWEEK(o.Order_Date,1)=YEARWEEK(CURDATE(),1)";
}

elseif($period=="monthly"){
    $whereCondition = "WHERE MONTH(o.Order_Date)=MONTH(CURDATE()) 
                       AND YEAR(o.Order_Date)=YEAR(CURDATE())";
}

elseif($period=="yearly"){

    if($month){
        $whereCondition = "WHERE YEAR(o.Order_Date)=YEAR(CURDATE())
                           AND MONTH(o.Order_Date)='$month'";
    }
    else{
        $whereCondition = "WHERE YEAR(o.Order_Date)=YEAR(CURDATE())";
    }

}

/* ================= CATEGORY REVENUE ================= */

$query="

SELECT 
c.Category_Name,
SUM(oi.Quantity * oi.Price_Snapshot) AS revenue

FROM order_item oi
JOIN product_details p ON oi.Product_Id = p.Product_Id
JOIN category_details c ON p.Category_Id = c.Category_Id
JOIN `order` o ON oi.Order_Id = o.Order_Id

$whereCondition

GROUP BY c.Category_Id
ORDER BY revenue DESC

";

$result = mysqli_query($connection,$query);

$totalRevenue = 0;
$rows = [];

while($r = mysqli_fetch_assoc($result)){

    $rows[] = $r;
    $totalRevenue += $r['revenue'];

}

/* ================= TABLE HTML ================= */

$tableRows = "";

foreach($rows as $r){

$tableRows .= "

<tr>
<td>{$r['Category_Name']}</td>
<td>₹".number_format($r['revenue'],2)."</td>
</tr>

";

}

/* ================= CHART ================= */

$chartHTML = "";

if($chart){

$chartHTML = "<img src='$chart' style='width:450px;margin:20px auto;display:block;'>";

}

/* ================= HTML TEMPLATE ================= */

$html = "

<style>

body{
font-family: Arial, sans-serif;
color:#333;
}

.header{
text-align:left;
margin-bottom:10px;
}

.title{
color:#7e2626;
font-size:22px;
margin-top:10px;
}

.summary{
margin-top:10px;
}

table{
width:100%;
border-collapse:collapse;
margin-top:15px;
}

th{
background:#7e2626;
color:white;
padding:8px;
border:1px solid #ddd;
}

td{
padding:7px;
border:1px solid #ddd;
text-align:center;
}

</style>

<div class='header'>

<h2>GiftShop</h2>

<p>
201/A, Maninagar, Ahmedabad<br>
Email: giftshopmanigar@gmail.com | Phone: 9876543210
</p>

</div>

<hr>

<div class='title'>
Category Revenue Report
</div>

<p>
Generated: ".date("d M Y H:i")."<br>
Generated By: Admin
</p>

<table>

<tr>
<th>Total Revenue</th>
<th>Report Range</th>
</tr>

<tr>
<td>₹".number_format($totalRevenue,2)."</td>
<td>$reportRange</td>
</tr>

</table>

$chartHTML

<h3>Category Revenue</h3>

<table>

<tr>
<th>Category</th>
<th>Revenue</th>
</tr>

$tableRows

<tr>
<td style='font-weight:bold'>Total</td>
<td style='font-weight:bold'>₹".number_format($totalRevenue,2)."</td>
</tr>

</table>

";

/* ================= PDF ================= */

$dompdf = new Dompdf();

$dompdf->loadHtml($html);

$dompdf->setPaper('A4','portrait');

$dompdf->render();

$dompdf->stream("category_revenue_report.pdf",["Attachment"=>0]);

?>