<?php
date_default_timezone_set("Asia/Kolkata");

require_once '../../dompdf/autoload.inc.php';

use Dompdf\Dompdf;
use Dompdf\Options;

include("../db.php");

/* ================= FETCH DATA ================= */

$query = mysqli_query($connection,"
SELECT 
YEAR(Order_Date) AS year,
COUNT(Order_Id) AS total_orders,
SUM(Total_Amount) AS total_revenue
FROM `order`
WHERE Status='CONFIRM'
GROUP BY YEAR(Order_Date)
ORDER BY YEAR(Order_Date)
");

$rows = "";
$totalOrders = 0;
$totalRevenue = 0;

while($row=mysqli_fetch_assoc($query)){

$year = $row['year'];
$orders = $row['total_orders'];
$revenue = $row['total_revenue'];

$totalOrders += $orders;
$totalRevenue += $revenue;

$rows .= "
<tr>
<td>$year</td>
<td>$orders</td>
<td>₹".number_format($revenue,2)."</td>
</tr>
";
}

/* ================= CHART IMAGE ================= */

$chartImage = $_POST['chart_image'] ?? "";

/* ================= HTML ================= */
$logoPath = __DIR__ . "/../../home page/logo.svg";

if(file_exists($logoPath)){
    $logoData = base64_encode(file_get_contents($logoPath));
    $logoPath = 'data:image/png;base64,' . $logoData;
}


$html = "

<style>

@page{
margin:15px 20px 70px 20px;
}

body{
font-family: DejaVu Sans, sans-serif;
font-size:12px;
color:#333;
}

/* HEADER */

.header{
border-bottom:2px solid #7e2626;
padding-bottom:8px;
margin-bottom:12px;
position:relative;
padding-left:80px; /* space for logo */
min-height:70px;
}

.header img{
position:absolute;
left: -10px;
top: -10px;
height:55px;
}

.company h2{
margin:0;
color:#7e2626;
font-size:18px;
}

.company div{
font-size:11px;
margin-top:2px;
}

/* META */

.meta{
font-size:11px;
margin-top:6px;
}

/* SUMMARY */

.summary{
background:#f8f3ee;
padding:6px;
margin:10px 0;
font-size:12px;
border-left:4px solid #7e2626;
}

/* CHART */

.chart{
text-align:center;
margin:12px 0;
}

/* TABLE */

table{
width:100%;
border-collapse:collapse;
margin-top:10px;
page-break-inside:auto;
}

tr{
page-break-inside:avoid;
}

thead{
display:table-header-group;
}

tfoot{
display:table-footer-group;
}

th{
background:#7e2626;
color:white;
padding:6px;
font-size:12px;
}

td{
padding:5px;
border:1px solid #ddd;
font-size:11px;
text-align:center;
}

/* FOOTER */

.footer{
position:fixed;
bottom:-40px;
left:0;
right:0;
text-align:center;
font-size:10px;
color:#666;
border-top:1px solid #ccc;
}
.header img{
height:50px;
}

</style>
<div class='header'>
<img src='$logoPath'>

<div class='company'>
<h2>GiftShop</h2>
<div>201/A, Maninagar, Ahmedabad</div>
<div>Email: giftshopmaninagar@gmail.com | Phone: 9876543210</div>
</div>

</div>




<h3>Year Wise Revenue Report</h3>

<div class='meta'>
Generated : ".date("d M Y h:i A")."
</div>

<div class='summary'>
<b>Total Orders :</b> $totalOrders
&nbsp;&nbsp;&nbsp;
<b>Total Revenue :</b> ₹".number_format($totalRevenue,2)."
</div>
";

/* ================= ADD CHART ================= */


if($chartImage){

$html .= "
<div class='chart'>
<img src='$chartImage' width='420'>
</div>
";

}

$html .= "

<table>

<thead>
<tr>
<th>Year</th>
<th>Orders</th>
<th>Revenue</th>
</tr>
</thead>

<tbody>

$rows

</tbody>

<tfoot>

<tr>
<td colspan='2' style='text-align:right;font-weight:bold;background:#f8f3ee'>
Total Revenue
</td>

<td style='font-weight:bold;background:#f8f3ee'>
₹".number_format($totalRevenue,2)."
</td>

</tr>

</tfoot>

</table>

<div class='footer'>
Generated by GiftShop Admin Panel
</div>

";

/* ================= GENERATE PDF ================= */
$options = new Options();
$options->set('isRemoteEnabled', true);
$options->set('isHtml5ParserEnabled', true);


$dompdf = new Dompdf($options);

$dompdf->loadHtml($html);
$dompdf->setPaper('A4','portrait');

$dompdf->render();

$dompdf->stream("year_revenue_report.pdf",["Attachment"=>0]);

?>
