<?php
date_default_timezone_set("Asia/Kolkata");

require_once '../../dompdf/autoload.inc.php';
use Dompdf\Dompdf;
use Dompdf\Options;

include("../db.php");

/* ================= GET FILTER VALUES ================= */

$period = $_POST['period'] ?? '';
$month  = $_POST['month'] ?? '';

/* ================= REPORT NAME ================= */

$reportName = "Area-wise Orders Report";

if($period=="daily")   $reportName="Daily Area-wise Orders Report";
if($period=="weekly")  $reportName="Weekly Area-wise Orders Report";
if($period=="monthly") $reportName="Monthly Area-wise Orders Report";
if($period=="yearly")  $reportName="Yearly Area-wise Orders Report";

if($period=="yearly" && $month){
$reportName .= " - ".date("F", mktime(0,0,0,$month,10));
}

/* ================= FILTER CONDITION ================= */

$whereCondition="WHERE 1";

if($period=="daily"){
$whereCondition.=" AND DATE(o.Order_Date)=CURDATE()";
}

elseif($period=="weekly"){
$whereCondition.=" AND YEARWEEK(o.Order_Date,1)=YEARWEEK(CURDATE(),1)";
}

elseif($period=="monthly"){
$whereCondition.=" AND MONTH(o.Order_Date)=MONTH(CURDATE())
AND YEAR(o.Order_Date)=YEAR(CURDATE())";
}

elseif($period=="yearly"){

$whereCondition.=" AND YEAR(o.Order_Date)=YEAR(CURDATE())";

if($month){
$whereCondition.=" AND MONTH(o.Order_Date)='$month'";
}

}

/* ================= FETCH AREA DATA ================= */

$query = mysqli_query($connection,"
SELECT 
a.Area_Name,
o.Order_Id,
CONCAT(u.First_Name,' ',u.Last_Name) AS customer,
DATE(o.Order_Date) AS order_date
FROM `order` o
JOIN user_details u ON o.User_Id = u.User_Id
JOIN area_details a ON u.Area_Id = a.Area_Id
$whereCondition
ORDER BY a.Area_Name , o.Order_Date DESC
");

/* ================= GENERATE TABLE ROWS ================= */

$currentArea="";
$rows="";
$totalOrders=0;

while($row=mysqli_fetch_assoc($query)){

$totalOrders++;

if($currentArea != $row['Area_Name']){

$currentArea = $row['Area_Name'];

$rows .= "
<tr class='area-row'>
<td colspan='3'>Area : $currentArea</td>
</tr>
";
}

$rows .= "
<tr>
<td>{$row['Order_Id']}</td>
<td>{$row['customer']}</td>
<td>{$row['order_date']}</td>
</tr>
";
}

/* ================= CHART IMAGE ================= */

$chartImage = $_POST['chart_image'] ?? "";
// LOGO 
$logoPath = __DIR__ . "/../../home page/logo.svg";

if(file_exists($logoPath)){
$logoData=base64_encode(file_get_contents($logoPath));
$logoPath='data:image/png;base64,'.$logoData;
}
/* ================= PDF HTML ================= */

$html="

<style>

@page{
margin:15px 20px 70px 20px;
}

body{
font-family: DejaVu Sans, sans-serif;
font-size:12px;
color:#333;
}

/* HEADER */

.header{
border-bottom:2px solid #7e2626;
padding-bottom:8px;
margin-bottom:12px;
position:relative;
padding-left:80px;
min-height:70px;
}

.header img{
position:absolute;
left:-10px;
top:-10px;
height:50px;
}

.company h2{
margin:0;
color:#7e2626;
font-size:18px;
}

.company div{
font-size:11px;
margin-top:2px;
}

.meta{
font-size:11px;
margin-top:6px;
}

/* SUMMARY */

.summary{
background:#f8f3ee;
padding:6px;
margin:10px 0;
font-size:12px;
border-left:4px solid #7e2626;
}

/* TABLE */

table{
width:100%;
border-collapse:collapse;
margin-top:10px;
page-break-inside:auto;
}

tr{
page-break-inside:avoid;
page-break-after:auto;
}

td,th{
page-break-inside:avoid;
}

thead{
display:table-header-group;
}

tfoot{
display:table-footer-group;
}

.area-row{
background:#f8f3ee;
font-weight:bold;
color:#7e2626;
}

th{
background:#7e2626;
color:white;
padding:6px;
font-size:12px;
}

td{
padding:5px;
border:1px solid #ddd;
font-size:11px;
text-align:center;
}

/* CHART */

.chart{
text-align:center;
margin:12px 0;
}

/* FOOTER */

.footer{
position:fixed;
bottom:-40px;
left:0;
right:0;
text-align:center;
font-size:10px;
color:#666;
border-top:1px solid #ccc;
}

</style>

<div class='header'>

<img src='$logoPath'>

<div class='company'>

<h2>GiftShop</h2>

<div>201/A,Business Park,GiftShop,Maninagar,Ahmedabad,Gujarat</div>

<div>Email: giftshopmaninagar@gmail.com | Phone:+91 9876543210</div>

</div>

</div>

<h3>$reportName</h3>

<div class='meta'>
Generated : ".date("d M Y h:i A")."
</div>

<div class='summary'>
<b>Total Orders :</b> $totalOrders
</div>
";

/* ================= ADD CHART ================= */

if($chartImage){
$html .= "
<div class='chart'>
<img src='$chartImage' width='420'>
</div>
";
}

$html .= "

<table>

<thead>
<tr>
<th>Order ID</th>
<th>Customer</th>
<th>Date</th>
</tr>
</thead>

<tbody>

$rows

</tbody>

<tfoot>
<tr>
<td colspan='2' style='text-align:right;font-weight:bold;background:#f8f3ee'>
Total Orders
</td>
<td style='font-weight:bold;background:#f8f3ee'>
$totalOrders
</td>
</tr>
</tfoot>

</table>

<div class='footer'>
Generated by GiftShop Admin Panel
</div>
";

/* ================= GENERATE PDF ================= */

$options = new Options();
$options->set('isRemoteEnabled', true);

$dompdf = new Dompdf($options);

$dompdf->loadHtml($html);
$dompdf->setPaper('A4','portrait');
$dompdf->render();

$dompdf->stream("area-wise_orders_report.pdf",["Attachment"=>0]);
?>